name: CoffeeShops
options:
  bundleIdPrefix: dk.simonbs
targets:
  CoffeeShops:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources: CoffeeShops
    postCompileScripts:
    - name: Run SwiftLint
      path: scripts/swiftlint.sh
      basedOnDependencyAnalysis: false
    dependencies:
    - package: Authentication
      product: AuthenticationData
    - package: Authentication
      product: AuthenticationDomain
    - package: DB
      product: DB
    - package: DB
      product: SwiftDataDB
    - package: MapsAppOpener
      product: MapsAppOpenerData
    - package: MapFeature
      product: MapFeatureData
    - package: MapFeature
      product: MapFeatureUI
    - package: ProfileFeature
      product: ProfileFeatureData
    - package: ProfileFeature
      product: ProfileFeatureUI
    - package: OnboardingFeature
      product: OnboardingFeatureUI
    - package: DetailsFeature
      product: DetailsFeatureData
    - package: DetailsFeature
      product: DetailsFeatureDomain
    - package: DetailsFeature
      product: DetailsFeatureUI
    scheme:
      testPlans:
      - path: CoffeeShops/TestPlan.xctestplan
  OnboardingDevApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources: 
      - path: DevApps/OnboardingDevApp
        group: DevApps
    dependencies:
      - package: OnboardingFeature
        product: OnboardingFeatureUI
  DetailsDevApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources: 
      - path: DevApps/DetailsDevApp
        group: DevApps
    dependencies:
      - package: DetailsFeature
        product: DetailsFeatureDomain
      - package: DetailsFeature
        product: DetailsFeatureUI
      - package: MapsAppOpener
        product: MapsAppOpenerData
  MapDevApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: DevApps/MapDevApp
        group: DevApps
    dependencies:
      - package: MapFeature
        product: MapFeatureDomain
      - package: MapFeature
        product: MapFeatureUI
  ProfileDevApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: DevApps/ProfileDevApp
        group: DevApps
    dependencies:
      - package: Authentication
        product: AuthenticationDomain
      - package: MapsAppOpener
        product: MapsAppOpenerData
      - package: ProfileFeature
        product: ProfileFeatureUI
configFiles:
  Debug: Configs/Base.xcconfig
  Release: Configs/Base.xcconfig
fileGroups:
  - project.yml
  - Configs/Base.xcconfig
packages:
  AnyAsync:
    path: Packages/AnyAsync
  Authentication:
    path: Packages/Authentication
  DB:
    path: Packages/DB
  MapsAppOpener:
    path: Packages/MapsAppOpener
  OnboardingFeature:
    path: Packages/OnboardingFeature
  DetailsFeature:
    path: Packages/DetailsFeature
  MapFeature:
    path: Packages/MapFeature
  ProfileFeature:
    path: Packages/ProfileFeature
