name: CoffeeShops
options:
  bundleIdPrefix: dk.simonbs
targets:
  CoffeeShops:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources: CoffeeShops
    settings:
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
    postCompileScripts:
    - name: Run SwiftLint
      path: scripts/swiftlint.sh
      basedOnDependencyAnalysis: false
    dependencies:
    - package: Authentication
      product: AuthenticationData
    - package: Authentication
      product: AuthenticationDomain
    - package: DB
      product: DB
    - package: DB
      product: SwiftDataDB
    - package: MapsLauncher
      product: MapsLauncherData
    - package: MapFeature
      product: MapFeatureData
    - package: MapFeature
      product: MapFeatureUI
    - package: ProfileFeature
      product: ProfileFeatureData
    - package: ProfileFeature
      product: ProfileFeatureUI
    - package: OnboardingFeature
      product: OnboardingFeatureUI
    - package: DetailsFeature
      product: DetailsFeatureData
    - package: DetailsFeature
      product: DetailsFeatureDomain
    - package: DetailsFeature
      product: DetailsFeatureUI
    scheme:
      testPlans:
      - path: CoffeeShops/TestPlan.xctestplan
  OnboardingDevApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources: 
      - path: DevApps/OnboardingDevApp
        group: DevApps
    settings:
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
    dependencies:
      - package: OnboardingFeature
        product: OnboardingFeatureUI
  DetailsDevApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources: 
      - path: DevApps/DetailsDevApp
        group: DevApps
    settings:
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
    dependencies:
      - package: DetailsFeature
        product: DetailsFeatureDomain
      - package: DetailsFeature
        product: DetailsFeatureUI
      - package: MapsLauncher
        product: MapsLauncherData
  MapDevApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: DevApps/MapDevApp
        group: DevApps
    settings:
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
    dependencies:
      - package: MapFeature
        product: MapFeatureDomain
      - package: MapFeature
        product: MapFeatureUI
  ProfileDevApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: DevApps/ProfileDevApp
        group: DevApps
    settings:
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
    dependencies:
      - package: Authentication
        product: AuthenticationDomain
      - package: MapsLauncher
        product: MapsLauncherData
      - package: ProfileFeature
        product: ProfileFeatureUI
settings:
  CURRENT_PROJECT_VERSION: 1
  MARKETING_VERSION: "1.0"
  ENABLE_USER_SCRIPT_SANDBOXING: NO
  ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
fileGroups:
  - project.yml
packages:
  AnyAsync:
    path: Packages/AnyAsync
  Authentication:
    path: Packages/Authentication
  DB:
    path: Packages/DB
  MapsLauncher:
    path: Packages/MapsLauncher
  OnboardingFeature:
    path: Packages/OnboardingFeature
  DetailsFeature:
    path: Packages/DetailsFeature
  MapFeature:
    path: Packages/MapFeature
  ProfileFeature:
    path: Packages/ProfileFeature
