name: SwiftLint
on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, synchronize]
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  SwiftLint:
    runs-on: shape
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: SwiftLint
        run: swiftlint --quiet --reporter github-actions-logging
